### ISSUE TITLE
Do I need to worry about memory leaks? ( e.g. [unowned self], [weak self] )

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [onmyway133/EasyClosure#2]
Do I need to worry about memory leaks?
Following code would be fine?
 ```
button.on.tap {
            self.button.isSelected.toggle()
        }
```
or do I need to put [unowned self], as following?
```
button.on.tap { [unowned self] in
            self.button.isSelected.toggle()
        }
```

**Comment by onmyway133** [comment]
@Rashesh-Bosamiya If `self` is keeping `button`, then you need `weak/unowned`, that's where the `escaping` warns us about
